<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ModuleApp;
use Illuminate\Support\Facades\DB;

class Modules extends Seeder
{
    public function run()
    {

       $modulesExist = [
            [
             "id"=>"0fac",
             "name"=>"Inventarios",
             "deep"=>1,
             "root"=>"b599",
             "path"=>"inventories",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"13jl",
             "name"=>"Index",
             "deep"=>1,
             "root"=>"278j",
             "path"=>"manpower",
             "details"=>json_encode([]),
             "icon"=>"home"
            ],
            [
             "id"=>"189j",
             "name"=>"Crear",
             "deep"=>1,
             "root"=>"278j",
             "path"=>"manpower/create",
             "details"=>json_encode([]),
             "icon"=>"domain_add"
            ],
            [
             "id"=>"270b",
             "name"=>"Clientes",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"clients",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"278j",
             "name"=>"R.R.H.H",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"manpower",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"27bn",
             "name"=>"Reporte",
             "deep"=>1,
             "root"=>"278j",
             "path"=>"manpower/report",
             "details"=>json_encode([]),
             "icon"=>"show_chart"
            ],
            [
             "id"=>"27da",
             "name"=>"Ciclicos",
             "deep"=>2,
             "root"=>"0fac",
             "path"=>"cyclecount",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"42c9",
             "name"=>"Proveedores",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"providers",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"46d9",
             "name"=>"Producto",
             "deep"=>1,
             "root"=>"b599",
             "path"=>"warehouses/product",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"4a82",
             "name"=>"Presupuestos",
             "deep"=>0,
             "root"=>"BOF",
             "path"=>"budget",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"4bed",
             "name"=>"Preventa",
             "deep"=>0,
             "root"=>"BOF",
             "path"=>"preorders",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"4f36",
             "name"=>"Usuarios",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"usuarios",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"65af",
             "name"=>"POS",
             "deep"=>1,
             "root"=>"9f4f",
             "path"=>"pos",
             "details"=>json_encode([]),
             "icon"=>"point_of_sale"
            ],
            [
             "id"=>"8e26",
             "name"=>"Creditos",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"credits",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"972e",
             "name"=>"Crear",
             "deep"=>1,
             "root"=>"4f36",
             "path"=>"usuarios/create",
             "details"=>json_encode([]),
             "icon"=>"person_add"
            ],
            [
             "id"=>"9a66",
             "name"=>"Preventa",
             "deep"=>1,
             "root"=>"b599",
             "path"=>"almacenes/preventa",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"9af8",
             "name"=>"Compras",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"buys",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"9f4f",
             "name"=>"Ventas",
             "deep"=>0,
             "root"=>"BOF",
             "path"=>"sales",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"a04s",
             "name"=>"R.R.H.H",
             "deep"=>0,
             "root"=>"BOF",
             "path"=>"manpower",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"a13y",
             "name"=>"Dashboard",
             "deep"=>1,
             "root"=>"4bed",
             "path"=>"preorders/dashboard",
             "details"=>json_encode([]),
             "icon"=>"dashboard"
            ],
            [
             "id"=>"a313",
             "name"=>"Cajas",
             "deep"=>1,
             "root"=>"9f4f",
             "path"=>"sales/cashdesks",
             "details"=>json_encode([]),
             "icon"=>"point_of_sale"
            ],
            [
             "id"=>"a831",
             "name"=>"Configuracion",
             "deep"=>1,
             "root"=>"4bed",
             "path"=>"preorders/config",
             "details"=>json_encode([]),
             "icon"=>"settings"
            ],
            [
             "id"=>"ade8",
             "name"=>"Resurtido",
             "deep"=>1,
             "root"=>"b599",
             "path"=>"resurtido",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"b13n",
             "name"=>"Checkout",
             "deep"=>1,
             "root"=>"4bed",
             "path"=>"preorders/checkout",
             "details"=>json_encode([]),
             "icon"=>"point_of_sale"
            ],
            [
             "id"=>"b599",
             "name"=>"Almacenes",
             "deep"=>0,
             "root"=>"BOF",
             "path"=>"almacenes",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"bc02",
             "name"=>"Sucursales",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"stores",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"c26m",
             "name"=>"Puestos",
             "deep"=>2,
             "root"=>"4f36",
             "path"=>"usuarios/positions",
             "details"=>json_encode([]),
             "icon"=>"list"
            ],
            [
             "id"=>"c48e",
             "name"=>"Productos",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"products",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"d5c2",
             "name"=>"Equipo",
             "deep"=>0,
             "root"=>"BOF",
             "path"=>"teamplate",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"e13m",
             "name"=>"Index",
             "deep"=>1,
             "root"=>"4bed",
             "path"=>"preorders",
             "details"=>json_encode([]),
             "icon"=>"home"
            ],
            [
             "id"=>"fe42",
             "name"=>"Checador",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"assists",
             "details"=>json_encode([]),
             "icon"=>null
            ],
            [
             "id"=>"g17m",
             "name"=>"Pedidos",
             "deep"=>1,
             "root"=>"4bed",
             "path"=>"preorders/pedidos",
             "details"=>json_encode([]),
             "icon"=>"receipt_long"
            ],
            [
             "id"=>"j31v",
             "name"=>"Reportes",
             "deep"=>1,
             "root"=>"v76v",
             "path"=>"indicators/reports",
             "details"=>json_encode([]),
             "icon"=>"query_stats"
            ],
            [
             "id"=>"l02m",
             "name"=>"Almacen",
             "deep"=>1,
             "root"=>"4bed",
             "path"=>"preorders/warehouse",
             "details"=>json_encode([]),
             "icon"=>"warehouse"
            ],
            [
             "id"=>"r29j",
             "name"=>"Checkin",
             "deep"=>1,
             "root"=>"4bed",
             "path"=>"preorders/checkin",
             "details"=>json_encode([]),
             "icon"=>"fact_check"
            ],
            [
             "id"=>"rf23",
             "name"=>"Justificaciones",
             "deep"=>1,
             "root"=>"278j",
             "path"=>"manpower/justification",
             "details"=>json_encode([]),
             "icon"=>"subject"
            ],
            [
             "id"=>"u12y",
             "name"=>"Formularios",
             "deep"=>1,
             "root"=>"v76v",
             "path"=>"indicators/forms",
             "details"=>json_encode([]),
             "icon"=>"description"
            ],
            [
             "id"=>"v76v",
             "name"=>"Indicadores",
             "deep"=>0,
             "root"=>"CLU",
             "path"=>"indicators",
             "details"=>json_encode([]),
             "icon"=>"dashboard"
            ],
            [
             "id"=>"wj28",
             "name"=>"Branches",
             "deep"=>1,
             "root"=>"4f36",
             "path"=>"usuarios/branch",
             "details"=>json_encode([]),
             "icon"=>"person_pin"
            ],
            [
             "id"=>"y08i",
             "name"=>"Justificaciones",
             "deep"=>1,
             "root"=>"a04s",
             "path"=>"manpower/justifications",
             "details"=>json_encode([]),
             "icon"=>null
            ]
    ];

    DB::statement('SET SQL_SAFE_UPDATES= 0');
    DB::statement('SET FOREIGN_KEY_CHECKS = 0');

    $ins = ModuleApp::insert($modulesExist);

    DB::statement('SET SQL_SAFE_UPDATES= 1');
    DB::statement('SET FOREIGN_KEY_CHECKS = 1');


    }
}
